baseurl = "/"
title = "LINTENG'S BLOG"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Linteng Wang"
  bio = "Machine Learning Engineer working in NLP, news recommendation and LLM at Sina Weibo."
  avatar = "img/avatar.jpeg"

[Params]
  description = "Linteng's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  twitter_cards = true # Enable Twitter Cards if true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]

[Params.logo]
  subtitle = "坠欢莫拾，酒痕在衣。" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  cached = false
  twitter = "maillinteng"
  github = "wanglinteng"

[Params.widgets.search]
  url = "https://www.bing.com/search"
  [Params.widgets.search.input]
    name = "q1"
    pre = "site:"

